export const ONE_HOUR_IN_SECONDS = 60 * 60;
export const THIRTY_DAYS_IN_SECONDS = 30 * 24 * ONE_HOUR_IN_SECONDS;
export const ONE_MINUTE_IN_SECONDS = 1 * 60;
export const TWENTY_SECONDS_IN_SECONDS = 20;
